### PR TITLE
change getstate to reduce

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Out of curiosity, why do you prefer reduce over getstate @inducer?

**Comment by inducer** [comment]
`__getstate__` is stateful, and the implementation relies on "zapping" the correct attribute out of the pickled state. By comparison, the `__reduce__` has no way of being incorrect.

**Review by inducer — APPROVED** [review]
Sorry again for the extra effor.t

**Comment by matthiasdiener** [comment]
> `__getstate__` is stateful, and the implementation relies on "zapping" the correct attribute out of the pickled state. By comparison, the `__reduce__` has no way of being incorrect.

Ah, that makes sense. Thanks for the explanation!

**Pull request merged**
